# Generated by Django 3.2.5 on 2021-07-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210725_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
