# Generated by Django 3.2.5 on 2021-07-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('VH', 'Vehicles'), ('FS', 'Fashion'), ('BK', 'Books'), ('EC', 'Electronics'), ('CA', 'Collectibles & Art'), ('HA', 'Home Appliances'), ('TH', 'Toys & Hobbies'), ('HB', 'Health and Beauty'), ('UC', 'Uncategorized')], max_length=2),
        ),
    ]
