# Generated by Django 3.2.5 on 2021-07-27 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210726_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='is_highest',
        ),
    ]
