# Generated by Django 3.2.5 on 2021-07-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_bid_is_highest'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
